all:
  hosts:
    postgres_server:
      ansible_host: 82.117.87.172
    gitlab_server:
      ansible_host: 82.202.138.79
    jenkins_server:
      ansible_host: 176.109.101.38
    gitlab_runner_server:
      ansible_host: 176.109.101.38

posgress_app:
  hosts:
    postgres_server:

gitlab:
  hosts:
    gitlab_server:

jenkins:
  hosts:
    jenkins_server:

gitlab_runners:
  hosts:
    gitlab_runner_server: