---

name: 'Install nano and vi'
becomes: true
hosts: all

tasks:
  - name: 'Gettings facts'
    ansible.builtin.package_facts:
      manager: auto

  - name: 'Install nano'
    ansible.builtin.package:
      name: nano
      state: present
    when: "'nano' not in package_facts.packages"
    register: result_nano
  
  - name: "Nano already installed in host"
    degug:
      msg: "Nano already installed in host"
    when: "'nano' in package_facts.packages"
  
  - name: "Nano intalled"
    debug:
      msg: "Nano was install"
    when: "result_nano.changed is defined and result_nano.changed"

  - name: 'Install vi'
    ansible.builtin.package:
      name: vi
      state: present
    when: "'vi' not in package_facts.packages"
    register: result_vi

  - name: "Vi already installed in host"
    degug:
      msg: "Nano already installed in host"
    when: "'vi' in package_facts.packages"

  - name: "Vi already installed in host"
    degug:
      msg: "Vi already installed in host"
    when: "'vi' in package_facts.packages"
  
  - name: "Vi intalled"
    debug:
      msg: "Vi was install"
    when: "result_vi.changed is defined and result_vi.changed"

  
