---
- name: 'Install nano and vim'
  become: yes
  hosts: all

  tasks:
    - name: 'Gettings facts'
      ansible.builtin.package_facts:
        manager: auto

    - name: 'Install nano'
      ansible.builtin.package:
        name: nano
        state: present
      when: "'nano' not in ansible_facts.packages"
      register: result_nano
    
    - name: "Nano already installed in host"
      debug:
        msg: "Nano already installed in host"
      when: "'nano' in ansible_facts.packages"
    
    - name: "Nano intalled"
      debug:
        msg: "Nano was install"
      when: "result_nano.changed is defined and result_nano.changed"

    - name: 'Install vim'
      ansible.builtin.package:
        name: vim
        state: present
      when: "'vim' not in ansible_facts.packages"
      register: result_vim

    - name: "vim already installed in host"
      debug:
        msg: "Nano already installed in host"
      when: "'vim' in ansible_facts.packages"

    - name: "vim already installed in host"
      debug:
        msg: "vim already installed in host"
      when: "'vim' in ansible_facts.packages"
    
    - name: "vim intalled"
      debug:
        msg: "vim was install"
      when: "result_vim.changed is defined and result_vim.changed"

  
